language: php

php:
  - 5.4

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

sudo: false

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

before_install: 
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit
