language: php

php:
  - 5.5

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

sudo: false

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

before_install: 
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - export COMPOSER_ROOT_VERSION=1.1.x-dev
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=bc8c8bf1d3a7e232fca5df78a0bfc0633d9e216d15339299af916f779040b861 ./bin/test-reporter
