parameters:
    open_orchestra_newsletter.display.newsletter.class: OpenOrchestra\Newsletter\DisplayBlock\Strategies\NewsletterStrategy

services:
    open_orchestra_newsletter.display.newsletter:
        class: %open_orchestra_newsletter.display.newsletter.class%
        arguments:
            - @form.factory
            - @request_stack
            - @router
            - @open_orchestra_newsletter.factory.newsletter_subscriber
            - @object_mananger
        tags:
            - { name: open_orchestra_display.display_block.strategy }
