parameters:
    open_orchestra_newsletter.generate_form.newsletter.class: OpenOrchestra\NewsletterAdminBundle\GenerateForm\NewsletterStrategy

services:
    open_orchestra_newsletter.generate_form.newsletter:
        class: %open_orchestra_newsletter.generate_form.newsletter.class%
        tags:
            - { name: open_orchestra_backoffice.generate_form.strategy }
